server:
  port: 8061

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
              

    
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: labresults-service
        uri: lb://labresults-service

predicates:
        - Path=/labresults/**
        filters:
        - RewritePath=/labresults/(?<path>.*), /$\{path}
#        - RewritePath=/labresults/(?.*), /$\{path}
#         - RewritePath=/labresults/(?<mrn>.*), /$\{mrn}
     
 
  

    
